# Workaround for https://github.com/tmux-plugins/tpm/issues/57
# https://turnspike.com/2017/03/13/byobu-and-tmux-plugin-manager-tpm/

# Then clone tpm to ~/.config/byobu/plugins/, e.g.
# git clone https://github.com/tmux-plugins/tpm ~/.config/byobu/plugins/tpm
set-environment -g TMUX_PLUGIN_MANAGER_PATH "~/.config/byobu/plugins/"

# Custom configuration
source ~/.config/byobu/plugins.tmux

unbind 'M-Left'
unbind 'M-Right'
unbind 'M-Up'
unbind 'M-Down'

unbind 'C-Left'
unbind 'C-Right'
unbind 'C-Up'
unbind 'C-Down'

# Smart pane switching with awareness of Vim splits.
# See: https://github.com/christoomey/vim-tmux-navigator
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|l?n?vim?x?)(diff)?$'"

bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h'  'select-pane -L'
bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j'  'select-pane -D'
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k'  'select-pane -U'
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l'  'select-pane -R'

bind-key -n 'M-H' if-shell "$is_vim" 'send-keys C-H'  'resize-pane -L 5'
bind-key -n 'M-J' if-shell "$is_vim" 'send-keys C-J'  'resize-pane -D 5'
bind-key -n 'M-K' if-shell "$is_vim" 'send-keys C-K'  'resize-pane -U 5'
bind-key -n 'M-L' if-shell "$is_vim" 'send-keys C-L'  'resize-pane -R 5'

tmux_version='$(tmux -V | sed -En "s/^tmux ([0-9]+(.[0-9]+)?).*/\1/p")'
if-shell -b '[ "$(echo "$tmux_version < 3.0" | bc)" = 1 ]' \
    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\'  'select-pane -l'"
if-shell -b '[ "$(echo "$tmux_version >= 3.0" | bc)" = 1 ]' \
    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\\\'  'select-pane -l'"

bind-key -T copy-mode-vi 'C-h' select-pane -L
bind-key -T copy-mode-vi 'C-j' select-pane -D
bind-key -T copy-mode-vi 'C-k' select-pane -U
bind-key -T copy-mode-vi 'C-l' select-pane -R
bind-key -T copy-mode-vi 'C-\' select-pane -l

# Byobu default, set in usr/share/byobu/profiles/tmux
# Formats see: https://www.man7.org/linux/man-pages/man1/tmux.1.html#FORMATS
set-option -g set-titles on
#set-option -g set-titles-string '#(whoami)@#H - byobu (#S)'
#set-option -g set-titles-string '#{session_path} - #(whoami)@#H - #W@byobu'
# set-option -g set-titles-string '#(whoami)@#H - #W@byobu'

# pane_title passes the original title (set by the shell)
#set-option -g set-titles-string '#{pane_title}@byobu'
set-option -g set-titles-string '#{pane_title}'

# Use fish shell
#set-option -g default-shell /bin/fish
set-option -g default-command /bin/fish
